using System;
using Newtonsoft.Json.Linq;

namespace SimulationCrew.AIBridge.Messages
{
    /// <summary>
    /// Represents a complete conversation turn response from the backend API.
    /// Contains the player's transcribed speech, NPC's text response, analysis results,
    /// and the NPC's audio response as base64-encoded data.
    /// Used for synchronous REST API conversations (not WebSocket streaming).
    /// </summary>
    [Serializable]
    public class ConversationTurnResponse
    {
        /// <summary>
        /// The transcribed text from the player's speech input.
        /// </summary>
        public string PlayerText;

        /// <summary>
        /// The NPC's text response generated by the LLM.
        /// </summary>
        public string NpcResponseText;

        /// <summary>
        /// Analysis results from the conversation evaluation system.
        /// Contains scores, feedback, and other evaluation metrics as a JSON object.
        /// </summary>
        public JObject AnalysisResults;

        /// <summary>
        /// The NPC's audio response as base64-encoded audio data.
        /// Can be decoded and played back through Unity's audio system.
        /// </summary>
        public string NpcAudioBase64;
    }
}