using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using NUnit.Framework;
using OpusSharp.Core;
using Tsc.AIBridge.Audio.Codecs;

namespace Tsc.AIBridge.Tests.Editor
{
    /// <summary>
    /// BUSINESS REQUIREMENT: <see cref="OpusStreamDecoder"/> must decode every Opus packet
    /// it receives, especially in production-shaped streams from Voxtral/Cartesia (PCM →
    /// our PCM→Opus→OGG packaging → client). A silent packet drop translates 1:1 to truncated
    /// NPC audio that users hear.
    ///
    /// WHY: A real session on 2026-05-13 17:42 had the backend send 30748 bytes of OGG/Opus
    /// for a 4046ms TTS response, but the client only played back ~1,99s of audio. The
    /// <see cref="OggOpusParser"/> production-shape tests prove the parser extracts all packets
    /// from such a stream — so the loss must occur AFTER parsing: either decoding fails
    /// silently for some packets, or every "OPUS_INVALID_PACKET" exception in
    /// <see cref="OpusStreamDecoder.ProcessData"/> is swallowed (regel 232-239: catch block
    /// drops the packet, logs only under verbose). This fixture verifies the contract end-to-end
    /// with REAL Opus packets (generated by OpusSharp, the exact encoder used in production).
    ///
    /// WHAT: Encode N PCM frames with a real OpusEncoder, wrap them in OGG container pages,
    /// feed the bytes to OpusStreamDecoder.ProcessData, count decoded samples on the
    /// OnAudioDecoded event. Assert the sample count matches what the encoder put in
    /// (minus the standard PreSkip).
    ///
    /// HOW: Use OpusSharp.Core directly (same library production uses). PCM input is a
    /// deterministic 440Hz sine wave so frames carry real content (silence frames can be
    /// only 1-2 bytes and trigger different code paths).
    ///
    /// SUCCESS CRITERIA:
    /// - 200 frames in → ≥ (200 × 960) − preSkip samples out
    /// - Zero invalid-packet drops detected (we count via a known marker: total samples
    ///   should be exactly 200×960 minus preSkip)
    /// - Drip-fed input produces the same sample count as a single ProcessData call
    ///
    /// BUSINESS IMPACT:
    /// - If a test fails, the decoder drops packets it shouldn't — explains the 50% audio
    ///   loss users hear with Voxtral/Cartesia TTS
    /// - If all tests pass, the decoder is innocent and the bug is upstream (server-side
    ///   packaging, WebSocket transport, or buffer/playback logic)
    /// </summary>
    [TestFixture]
    public class OpusStreamDecoderRoundtripTests
    {
        private const int SampleRate = 48000;     // Opus internal rate
        private const int Channels = 1;
        private const int FrameSize = 960;        // 20ms at 48kHz
        private const int DefaultPreSkip = 312;   // OpusStreamDecoder forces this when header says 0

        private const byte HeaderTypeBos = 0x02;
        private const byte HeaderTypeEos = 0x04;
        private const byte HeaderTypeNone = 0x00;

        private static readonly byte[] OggMagic = Encoding.ASCII.GetBytes("OggS");
        private static readonly byte[] OpusHeadMagic = Encoding.ASCII.GetBytes("OpusHead");
        private static readonly byte[] OpusTagsMagic = Encoding.ASCII.GetBytes("OpusTags");

        /// <summary>
        /// BUSINESS REQUIREMENT: All 200 valid Opus frames round-trip through encode→OGG→decode.
        ///
        /// WHY: This is the precise scenario for Voxtral production: ~200 packets at 20ms each
        ///      = 4 seconds of audio, the exact length of the truncated 17:42 turn.
        /// WHAT: Encode 200 frames, pack one-per-page (Voxtral shape), decode, verify sample count.
        /// </summary>
        [Test]
        public void Roundtrip_200OpusFrames_OnePerPage_DecodesAllExpectedSamples()
        {
            const int totalFrames = 200;
            var oggBytes = BuildRealOpusOggStream(totalFrames, framesPerPage: 1);

            var (decodedSamples, _) = DecodeStream(oggBytes);

            var expectedMinSamples = totalFrames * FrameSize - DefaultPreSkip;
            Assert.AreEqual(expectedMinSamples, decodedSamples,
                $"Expected {expectedMinSamples} PCM samples ({totalFrames} × {FrameSize} − {DefaultPreSkip} preSkip), " +
                $"decoded {decodedSamples}. " +
                $"A shortfall here means OpusStreamDecoder is silently dropping packets — " +
                $"this would explain why production sessions hear only ~50% of NPC audio.");
        }

        /// <summary>
        /// BUSINESS REQUIREMENT: Same 200 frames packed two per page must produce same audio.
        ///
        /// WHY: Multi-packet pages are common in real encoders. If the parser+decoder pair
        ///      handles single-packet pages but loses one on multi-packet, we'd see ~50% loss.
        /// </summary>
        [Test]
        public void Roundtrip_200OpusFrames_TwoPerPage_DecodesAllExpectedSamples()
        {
            const int totalFrames = 200;
            var oggBytes = BuildRealOpusOggStream(totalFrames, framesPerPage: 2);

            var (decodedSamples, _) = DecodeStream(oggBytes);

            var expectedMinSamples = totalFrames * FrameSize - DefaultPreSkip;
            Assert.AreEqual(expectedMinSamples, decodedSamples,
                $"Two packets per page should decode identically to one packet per page. " +
                $"Got {decodedSamples}, expected {expectedMinSamples}.");
        }

        /// <summary>
        /// BUSINESS REQUIREMENT: Drip-feeding bytes (the realistic WebSocket case) must not lose audio.
        ///
        /// WHY: In production the OGG bytes arrive as many small WebSocket messages.
        ///      The decoder feeds them to its internal stream incrementally; if any state
        ///      transition between chunks loses a packet, we'd see partial audio.
        /// </summary>
        [Test]
        public void Roundtrip_DripFed_DecodesAllExpectedSamples()
        {
            const int totalFrames = 200;
            var oggBytes = BuildRealOpusOggStream(totalFrames, framesPerPage: 1);

            // Feed in irregular chunks like WebSocket frame jitter
            var chunkSizes = new[] { 47, 113, 13, 271, 5, 64, 1, 199, 33, 7 };
            var (decodedSamples, _) = DecodeStreamInChunks(oggBytes, chunkSizes);

            var expectedMinSamples = totalFrames * FrameSize - DefaultPreSkip;
            Assert.AreEqual(expectedMinSamples, decodedSamples,
                $"Drip-fed stream lost samples ({decodedSamples} vs {expectedMinSamples} expected). " +
                $"WebSocket chunking is the realistic delivery pattern — a loss here means production loses audio.");
        }

        /// <summary>
        /// DIAGNOSTIC: If the production bug is invalid-packet drops, this fixture would show
        /// the drop count. Currently OpusStreamDecoder has no public counter; if a future
        /// version exposes one, extend this test to assert zero drops.
        ///
        /// For now this test just confirms the OnAudioDecoded handler fires the expected
        /// number of times (one per successful decode).
        /// </summary>
        [Test]
        public void Roundtrip_200Frames_FiresOnAudioDecodedOncePerSuccessfulPacket()
        {
            const int totalFrames = 200;
            var oggBytes = BuildRealOpusOggStream(totalFrames, framesPerPage: 1);

            var (_, decodeCallbackCount) = DecodeStream(oggBytes);

            // PreSkip of 312 samples (< 960) fits in the first packet, so the first packet
            // is partially skipped but still emits remaining samples. Hence all 200 packets
            // should fire the callback.
            Assert.AreEqual(totalFrames, decodeCallbackCount,
                $"OnAudioDecoded fired {decodeCallbackCount} times for {totalFrames} encoded packets. " +
                $"A mismatch means some packets were dropped silently.");
        }

        // ---------- Encode + pack helpers ----------

        /// <summary>
        /// Encodes N frames of a 440Hz sine wave to Opus, then wraps them in an OGG/Opus stream
        /// (OpusHead BOS + OpusTags + audio pages + EOS). Returns the complete byte sequence
        /// ready to feed to OpusStreamDecoder.ProcessData.
        /// </summary>
        private static byte[] BuildRealOpusOggStream(int frameCount, int framesPerPage)
        {
            // Encode real Opus packets
            var opusPackets = EncodeOpusFrames(frameCount);

            // Pack into OGG
            using var stream = new MemoryStream();
            uint pageSeq = 0;
            const uint serial = 0xDECADEu;
            long granule = 0;

            // OpusHead and OpusTags headers
            WriteOggPage(stream, HeaderTypeBos, 0, serial, pageSeq++,
                segmentLengths: new byte[] { (byte)BuildOpusHeadPayload().Length },
                payload: BuildOpusHeadPayload());
            WriteOggPage(stream, HeaderTypeNone, 0, serial, pageSeq++,
                segmentLengths: new byte[] { (byte)BuildOpusTagsPayload().Length },
                payload: BuildOpusTagsPayload());

            // Audio data pages
            for (var i = 0; i < opusPackets.Count; i += framesPerPage)
            {
                var packetsThisPage = Math.Min(framesPerPage, opusPackets.Count - i);
                var segmentTable = new List<byte>();
                var combinedPayload = new List<byte>();

                for (var j = 0; j < packetsThisPage; j++)
                {
                    var packet = opusPackets[i + j];
                    // Build segment table for this packet (handles packets > 255 bytes
                    // even though Opus rarely produces them at this bitrate)
                    var remaining = packet.Length;
                    while (remaining >= 255)
                    {
                        segmentTable.Add(255);
                        remaining -= 255;
                    }
                    segmentTable.Add((byte)remaining);
                    combinedPayload.AddRange(packet);
                }

                granule += FrameSize * packetsThisPage;
                WriteOggPage(stream, HeaderTypeNone, granule, serial, pageSeq++,
                    segmentTable.ToArray(), combinedPayload.ToArray());
            }

            // EOS page
            WriteOggPage(stream, HeaderTypeEos, granule, serial, pageSeq,
                segmentLengths: Array.Empty<byte>(), payload: Array.Empty<byte>());

            return stream.ToArray();
        }

        /// <summary>
        /// Encodes <paramref name="frameCount"/> frames of a 440Hz sine wave to Opus.
        /// Uses the same OpusSharp library production uses. Returns real, decodable packets.
        /// </summary>
        private static List<byte[]> EncodeOpusFrames(int frameCount)
        {
            var encoder = new OpusEncoder(SampleRate, Channels, OpusPredefinedValues.OPUS_APPLICATION_VOIP);
            var packets = new List<byte[]>(frameCount);

            // 440Hz sine wave — gives the encoder real content to work with (avoiding the
            // trivial-silence path which may emit 1-byte packets that exercise different code).
            const float frequency = 440f;
            const float amplitude = 0.3f;
            var pcmFrame = new float[FrameSize * Channels];
            var encodeBuffer = new byte[4000];

            for (var f = 0; f < frameCount; f++)
            {
                for (var s = 0; s < FrameSize; s++)
                {
                    var t = (f * FrameSize + s) / (float)SampleRate;
                    pcmFrame[s] = amplitude * (float)Math.Sin(2 * Math.PI * frequency * t);
                }

                var encodedSize = encoder.Encode(pcmFrame, FrameSize, encodeBuffer, encodeBuffer.Length);
                var packet = new byte[encodedSize];
                Array.Copy(encodeBuffer, packet, encodedSize);
                packets.Add(packet);
            }

            return packets;
        }

        // ---------- Decode helpers ----------

        /// <summary>
        /// Pipes <paramref name="oggBytes"/> into OpusStreamDecoder in one call and counts
        /// total decoded samples + OnAudioDecoded callback invocations.
        /// </summary>
        private static (int decodedSamples, int callbackCount) DecodeStream(byte[] oggBytes)
        {
            using var decoder = new OpusStreamDecoder(isVerboseLogging: false);

            var totalSamples = 0;
            var callbackCount = 0;
            decoder.OnAudioDecoded += samples =>
            {
                totalSamples += samples.Length;
                callbackCount++;
            };

            decoder.ProcessData(oggBytes);
            return (totalSamples, callbackCount);
        }

        /// <summary>
        /// Feeds <paramref name="oggBytes"/> to OpusStreamDecoder in chunks sized per
        /// <paramref name="chunkSizes"/> (cycled). Mimics WebSocket fragmentation.
        /// </summary>
        private static (int decodedSamples, int callbackCount) DecodeStreamInChunks(byte[] oggBytes, int[] chunkSizes)
        {
            using var decoder = new OpusStreamDecoder(isVerboseLogging: false);

            var totalSamples = 0;
            var callbackCount = 0;
            decoder.OnAudioDecoded += samples =>
            {
                totalSamples += samples.Length;
                callbackCount++;
            };

            var offset = 0;
            var sizeIndex = 0;
            while (offset < oggBytes.Length)
            {
                var chunk = chunkSizes[sizeIndex++ % chunkSizes.Length];
                var actual = Math.Min(chunk, oggBytes.Length - offset);
                var slice = new byte[actual];
                Array.Copy(oggBytes, offset, slice, 0, actual);
                decoder.ProcessData(slice);
                offset += actual;
            }

            return (totalSamples, callbackCount);
        }

        // ---------- OGG page builder helpers ----------

        private static byte[] BuildOpusHeadPayload()
        {
            var p = new byte[19];
            Array.Copy(OpusHeadMagic, 0, p, 0, 8);
            p[8] = 1;     // version
            p[9] = (byte)Channels;
            // PreSkip = 312 (LE)
            p[10] = (byte)(DefaultPreSkip & 0xFF);
            p[11] = (byte)((DefaultPreSkip >> 8) & 0xFF);
            // Input sample rate = 48000 (LE)
            p[12] = (byte)(SampleRate & 0xFF);
            p[13] = (byte)((SampleRate >> 8) & 0xFF);
            p[14] = (byte)((SampleRate >> 16) & 0xFF);
            p[15] = (byte)((SampleRate >> 24) & 0xFF);
            p[16] = 0; p[17] = 0; // output gain
            p[18] = 0;            // channel mapping family
            return p;
        }

        private static byte[] BuildOpusTagsPayload()
        {
            const string vendor = "RoundtripTest";
            var vendorBytes = Encoding.UTF8.GetBytes(vendor);
            var p = new byte[8 + 4 + vendorBytes.Length + 4];
            Array.Copy(OpusTagsMagic, 0, p, 0, 8);
            p[8] = (byte)vendorBytes.Length;
            Array.Copy(vendorBytes, 0, p, 12, vendorBytes.Length);
            return p;
        }

        private static void WriteOggPage(MemoryStream output, byte headerType, long granule, uint serial, uint sequence,
            byte[] segmentLengths, byte[] payload)
        {
            var pageSize = 27 + segmentLengths.Length + payload.Length;
            var page = new byte[pageSize];
            var offset = 0;

            Array.Copy(OggMagic, 0, page, offset, 4); offset += 4;
            page[offset++] = 0; // OGG version
            page[offset++] = headerType;
            BitConverter.GetBytes(granule).CopyTo(page, offset); offset += 8;
            BitConverter.GetBytes(serial).CopyTo(page, offset); offset += 4;
            BitConverter.GetBytes(sequence).CopyTo(page, offset); offset += 4;
            page[offset++] = 0; page[offset++] = 0; page[offset++] = 0; page[offset++] = 0; // CRC slot
            page[offset++] = (byte)segmentLengths.Length;
            Array.Copy(segmentLengths, 0, page, offset, segmentLengths.Length); offset += segmentLengths.Length;
            Array.Copy(payload, 0, page, offset, payload.Length);

            var crc = ComputeOggCrc(page);
            BitConverter.GetBytes(crc).CopyTo(page, 22);

            output.Write(page, 0, page.Length);
        }

        private static readonly uint[] OggCrcTable = BuildOggCrcTable();

        private static uint[] BuildOggCrcTable()
        {
            var t = new uint[256];
            for (uint i = 0; i < 256; i++)
            {
                var r = i << 24;
                for (var j = 0; j < 8; j++)
                {
                    if ((r & 0x80000000U) != 0) r = (r << 1) ^ 0x04C11DB7U;
                    else r <<= 1;
                }
                t[i] = r;
            }
            return t;
        }

        private static uint ComputeOggCrc(byte[] page)
        {
            uint crc = 0;
            foreach (var b in page) crc = (crc << 8) ^ OggCrcTable[((crc >> 24) & 0xFF) ^ b];
            return crc;
        }
    }
}
